[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install", "cd backend && npm install", "cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "NODE_ENV=production node backend/server.js"
